# Generated by Django 4.0.3 on 2022-03-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sapid', models.CharField(max_length=500, unique=True)),
                ('Hostname', models.CharField(max_length=500, unique=True)),
                ('Loopback', models.CharField(max_length=500, unique=True)),
                ('Mac_address', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
