# Generated by Django 4.0.3 on 2022-03-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router_details',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
